### ISSUE TITLE
No Installation Tutorial

### ISSUE THREAD

**Issue by BrettKnoss** [glesica/Neo4j.jl#26]
I don't see a tutorial, including installation.  Does neo4j need to be installed?

**Comment by GearsAD** [comment]
Hi @BrettKnoss,

This is just the Neo4j client, but you can quickly install a Neo4j instance from [Dockerhub](https://hub.docker.com/_/neo4j?tab=description) (we use 3.5.x because I'm not sure on 4.x compatibility, e.g. the tag [3.5.31](https://hub.docker.com/layers/neo4j/library/neo4j/3.5.31/images/sha256-25617d08e2263f69341aac45b717f5f080f08ebd78157d4897bc33fe9b5a0266?context=explore)).

Alternatively you could:
- Install a local instance, e.g. 3.5 on Debian https://debian.neo4j.com/
- Try Neo4j Aura (haven't tried this yet - because of the 4.x compatibility question) https://neo4j.com/cloud/neo4j-aura 

Hope this helps! Let me know if you try the Aura approach, curious if that works.

**Comment by glesica** [comment]
@GearsAD beat me to it!
